# Auto-generated by build script. Scans plain source imports so PyInstaller
# can bundle modules hidden by PyArmor obfuscation (e.g. sqlite3).
import ast, pathlib
files = list(pathlib.Path('.').glob('*.py')) + list(pathlib.Path('backend').rglob('*.py'))
mods = set()
for f in files:
    try:
        tree = ast.parse(f.read_text(encoding='utf-8'))
    except Exception:
        continue
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            mods.update(a.name for a in n.names)
        elif isinstance(n, ast.ImportFrom) and n.module and n.level == 0:
            mods.add(n.module)
mods.update(['sqlite3', '_sqlite3'])
hiddenimports = sorted(mods)
